logging:
  version: 1
  formatters:
    simple:
      format: '%(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
  root:
    level: INFO
    handlers:
    - console
